version: "3"
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    env_file: .env
    container_name: trip-ads
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"